// Auto-generated by scripts/generate.js from taxonomy.config.json. Do not edit directly.

export interface CategoryDefinition {
  key: string;
  label: string;
  archive: boolean;
  description: string;
  examples: string[];
}

export const CONFIG = {
  actionLabel: 'Follow Up',
  reviewLabel: 'Review',
  labels: {
    action: 'Follow Up',
    review: 'Review',
    pending: 'Pending',
    receipts: 'Receipts',
    newsletter: 'Newsletter',
    notifications: 'Notifications',
  } as Record<string, string>,
  archiveMap: {
    pending: true,
    receipts: true,
    newsletter: true,
    notifications: true,
  } as Record<string, boolean>,
  thresholds: {
    requiresAction: 0.55,
    isImportant: 0.7,
    minConfidence: 0.6,
  },
  typesafe: {
    apiEndpoint: 'https://api.typesafe.ai/v1/systemone',
    model: 'jev-latest',
  },
  categories: [
  {
    "key": "pending",
    "label": "Pending",
    "archive": true,
    "description": "Awaiting reply, package delivery tracking, ticket response, or ongoing workflow resolution",
    "examples": [
      "We received your inquiry and will respond soon",
      "Your order has shipped and is on the way"
    ]
  },
  {
    "key": "receipts",
    "label": "Receipts",
    "archive": true,
    "description": "Financial receipts, payment confirmations, Stripe/bank alerts, subscription invoices, tickets, bookings",
    "examples": [
      "Your receipt from Acme Inc",
      "Payment confirmation for subscription"
    ]
  },
  {
    "key": "newsletter",
    "label": "Newsletter",
    "archive": true,
    "description": "Editorial content, digests, blogs, product release updates, marketing promotions, Substack",
    "examples": [
      "This week in Tech Digest",
      "Introducing our new feature v2.0"
    ]
  },
  {
    "key": "notifications",
    "label": "Notifications",
    "archive": true,
    "description": "Automated service notices, one-time verification codes, OTPs, password resets, GitHub/Jira mentions, security alerts",
    "examples": [
      "Your verification code is 582914",
      "Security alert: New login detected",
      "[GitHub] Pull request #123 merged"
    ]
  }
] as CategoryDefinition[],
} as const;
