import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const configPath = path.join(rootDir, 'taxonomy.config.json');
if (!fs.existsSync(configPath)) {
  console.error('[ERROR] taxonomy.config.json not found at ' + configPath);
  process.exit(1);
}

const configRaw = fs.readFileSync(configPath, 'utf8');
let config;
try {
  config = JSON.parse(configRaw);
} catch (err) {
  console.error('[ERROR] Failed to parse taxonomy.config.json:', err.message);
  process.exit(1);
}

// Character and format validations
const forbiddenChars = { '\u2014': 'em-dash', '\u2013': 'en-dash', '\u00B7': 'middle-dot' };
for (let i = 0; i < configRaw.length; i++) {
  const code = configRaw.charCodeAt(i);
  const ch = configRaw[i];
  if ((code >= 0x1F300 && code <= 0x1FAFF) || (code >= 0x2600 && code <= 0x27BF)) {
    console.error(`[ERROR] Emoji character detected in taxonomy.config.json: U+${code.toString(16)}`);
    process.exit(1);
  }
  if (forbiddenChars[ch]) {
    console.error(`[ERROR] Forbidden character detected in taxonomy.config.json: ${forbiddenChars[ch]}`);
    process.exit(1);
  }
}

if (!config.action_label || typeof config.action_label !== 'string') {
  console.error('[ERROR] action_label must be a non-empty string');
  process.exit(1);
}
if (!config.review_label || typeof config.review_label !== 'string') {
  console.error('[ERROR] review_label must be a non-empty string');
  process.exit(1);
}
if (!Array.isArray(config.categories) || config.categories.length < 2) {
  console.error('[ERROR] categories must be an array of at least 2 categories');
  process.exit(1);
}

for (const cat of config.categories) {
  if (!cat.key || !cat.label || typeof cat.description !== 'string' || !Array.isArray(cat.examples)) {
    console.error(`[ERROR] Category invalid: ${JSON.stringify(cat)}`);
    process.exit(1);
  }
}

// 1. Generate src/config.ts
const srcConfigContent = `// Auto-generated by scripts/generate.js from taxonomy.config.json. Do not edit directly.

export interface CategoryDefinition {
  key: string;
  label: string;
  archive: boolean;
  description: string;
  examples: string[];
}

export const CONFIG = {
  actionLabel: '${config.action_label}',
  reviewLabel: '${config.review_label}',
  labels: {
    action: '${config.action_label}',
    review: '${config.review_label}',
${config.categories.map((c) => `    ${c.key}: '${c.label}',`).join('\n')}
  } as Record<string, string>,
  archiveMap: {
${config.categories.map((c) => `    ${c.key}: ${Boolean(c.archive)},`).join('\n')}
  } as Record<string, boolean>,
  thresholds: {
    requiresAction: ${Number(config.thresholds.requires_action ?? 0.55)},
    isImportant: ${Number(config.thresholds.is_important ?? 0.70)},
    minConfidence: ${Number(config.thresholds.min_confidence ?? 0.60)},
  },
  typesafe: {
    apiEndpoint: 'https://api.typesafe.ai/v1/systemone',
    model: 'jev-latest',
  },
  categories: ${JSON.stringify(config.categories, null, 2)} as CategoryDefinition[],
} as const;
`;

fs.writeFileSync(path.join(rootDir, 'src', 'config.ts'), srcConfigContent, 'utf8');
console.log('[OK] Updated src/config.ts');

// 2. Generate gas/Code.gs
const gasCodeContent = `/**
 * Jev-Mail: Google Apps Script 24/7 Cloud Automation
 *
 * Runs automatically on Google Cloud infrastructure via time-driven triggers.
 * Triages, labels, prioritizes, and archives incoming emails using TypeSafe Jev.
 *
 * Setup:
 * 1. Open https://script.google.com and create a project named Jev-Mail-Triage.
 * 2. Paste this Code.gs content.
 * 3. In Project Settings, add Script Property: TYPESAFE_API_KEY.
 * 4. Run installTrigger once from the function dropdown.
 */

var CONFIG = {
  actionLabel: '${config.action_label}',
  reviewLabel: '${config.review_label}',
  labels: {
${config.categories.map((c) => `    ${c.key}: '${c.label}',`).join('\n')}
  },
  archiveMap: {
${config.categories.map((c) => `    ${c.key}: ${Boolean(c.archive)},`).join('\n')}
  },
  thresholds: {
    requiresAction: ${Number(config.thresholds.requires_action ?? 0.55)},
    isImportant: ${Number(config.thresholds.is_important ?? 0.70)},
    minConfidence: ${Number(config.thresholds.min_confidence ?? 0.60)},
  },
  typesafeEndpoint: 'https://api.typesafe.ai/v1/systemone',
  model: 'jev-latest',
  maxBatchSize: 10,
};

/**
 * Installs a time-driven trigger running autoTriageInbox every 5 minutes.
 */
function installTrigger() {
  var triggers = ScriptApp.getProjectTriggers();
  for (var i = 0; i < triggers.length; i++) {
    ScriptApp.deleteTrigger(triggers[i]);
  }

  ScriptApp.newTrigger('autoTriageInbox')
    .timeBased()
    .everyMinutes(5)
    .create();

  Logger.log('[OK] 24/7 trigger installed successfully (interval: 5 minutes).');
}

/**
 * Validates whether TYPESAFE_API_KEY is configured in Script Properties.
 */
function setApiKey() {
  var key = PropertiesService.getScriptProperties().getProperty('TYPESAFE_API_KEY');
  if (!key) {
    Logger.log('[WARN] Please set TYPESAFE_API_KEY in Script Properties.');
  } else {
    Logger.log('[OK] TYPESAFE_API_KEY is configured.');
  }
}

/**
 * Main trigger function: triages unhandled emails in INBOX.
 */
function autoTriageInbox() {
  var apiKey = PropertiesService.getScriptProperties().getProperty('TYPESAFE_API_KEY');
  if (!apiKey) {
    Logger.log('[ERROR] TYPESAFE_API_KEY script property is missing.');
    return;
  }

  var threads = GmailApp.search('in:inbox', 0, CONFIG.maxBatchSize);
  if (threads.length === 0) {
    Logger.log('[INFO] Inbox empty. Zero-Inbox maintained.');
    return;
  }

  var labelObjects = getOrCreateLabels();

  for (var i = 0; i < threads.length; i++) {
    var thread = threads[i];
    var messages = thread.getMessages();
    var latestMessage = messages[messages.length - 1];

    if (hasAnySystemLabel(thread, labelObjects)) {
      continue;
    }

    var emailData = {
      sender: latestMessage.getFrom(),
      subject: latestMessage.getSubject(),
      snippet: latestMessage.getPlainBody().substring(0, 1000),
      has_attachment: latestMessage.getAttachments().length > 0,
    };

    try {
      var decision = callJevTriage(emailData, apiKey);
      applyDecision(thread, latestMessage, decision, labelObjects);
      Logger.log('[PROCESSED] [' + decision.targetLabel + '] ' + emailData.subject);
    } catch (err) {
      Logger.log('[ERROR] ' + emailData.subject + ': ' + err.toString());
    }
  }
}

/**
 * Historical Zero-Inbox Triage:
 * Re-triages all existing inbox emails without adding Star or Follow Up labels.
 */
function triageHistoricalInbox(maxThreads) {
  maxThreads = maxThreads || 100;
  var apiKey = PropertiesService.getScriptProperties().getProperty('TYPESAFE_API_KEY');
  if (!apiKey) {
    Logger.log('[ERROR] TYPESAFE_API_KEY script property is missing.');
    return;
  }

  var threads = GmailApp.search('in:inbox', 0, maxThreads);
  Logger.log('[INFO] Historical triage initiated: ' + threads.length + ' threads found.');
  if (threads.length === 0) {
    Logger.log('[INFO] Inbox already empty. Zero-Inbox maintained.');
    return;
  }

  var labelObjects = getOrCreateLabels();
  var actionLabelObj = labelObjects[CONFIG.actionLabel];
  var processed = 0;

  for (var i = 0; i < threads.length; i++) {
    var thread = threads[i];
    var messages = thread.getMessages();
    var latestMessage = messages[messages.length - 1];

    if (actionLabelObj && threadHasLabel(thread, actionLabelObj)) {
      thread.removeLabel(actionLabelObj);
    }

    var existingLabel = getExistingCategoryLabel(thread, labelObjects);
    if (existingLabel) {
      thread.moveToArchive();
      processed++;
      Logger.log('[' + processed + '/' + threads.length + '] Existing label archived: [' + existingLabel + '] ' + latestMessage.getSubject());
      continue;
    }

    var emailData = {
      sender: latestMessage.getFrom(),
      subject: latestMessage.getSubject(),
      snippet: latestMessage.getPlainBody().substring(0, 1000),
      has_attachment: latestMessage.getAttachments().length > 0,
    };

    try {
      var decision = callJevHistoricalTriage(emailData, apiKey);
      var label = labelObjects[decision.targetLabel];
      if (label) {
        thread.addLabel(label);
      }
      thread.moveToArchive();

      processed++;
      Logger.log('[' + processed + '/' + threads.length + '] Labeled & archived: [' + decision.targetLabel + '] ' + emailData.subject);
    } catch (err) {
      Logger.log('[ERROR] ' + emailData.subject + ': ' + err.toString());
    }
  }

  Logger.log('[DONE] Historical triage completed: ' + processed + ' threads processed.');
}

/**
 * Calls TypeSafe Jev System One model.
 */
function callJevTriage(emailData, apiKey) {
  var payload = {
    model: CONFIG.model,
    state: {
      email: emailData,
    },
    questions: {
      requires_action: {
        type: 'noul',
        instructions:
          'Does \`email\` clearly require the recipient to directly reply, make a decision, approve an item, or perform an ongoing task? Note: one-time verification codes, OTPs, login alerts, and automated notices do not require task follow-up.',
      },
      is_important: {
        type: 'noul',
        instructions:
          'Is this email high-priority, time-sensitive (handling needed within 24 hours), or from an important stakeholder requiring urgent attention?',
      },
      bucket: {
        type: 'choice',
        instructions:
          'If this email does not require direct action, which category does it primarily belong to?',
        criteria: {
${config.categories.map((c) => `          ${c.key}: ${JSON.stringify(c.description)},`).join('\n')}
        },
      },
    },
  };

  var options = {
    method: 'post',
    contentType: 'application/json',
    headers: {
      Authorization: 'Bearer ' + apiKey,
    },
    payload: JSON.stringify(payload),
    muteHttpExceptions: true,
  };

  var response = UrlFetchApp.fetch(CONFIG.typesafeEndpoint, options);
  var json = JSON.parse(response.getContentText());

  if (!json.answers) {
    throw new Error('TypeSafe API response error: ' + response.getContentText());
  }

  var answers = json.answers;
  var reqAction = answers.requires_action.noul;
  var isImportant = answers.is_important.noul;
  var bucket = answers.bucket.choice;
  var bucketConf = answers.bucket.confidence || 1.0;

  // 1. Action required: retain in Inbox, star if important
  if (reqAction >= CONFIG.thresholds.requiresAction) {
    var important = isImportant >= CONFIG.thresholds.isImportant;
    return { targetLabel: CONFIG.actionLabel, shouldStar: important, shouldArchive: false };
  }

  // 2. Non-action with low category confidence: fallback to Review
  if (bucketConf < CONFIG.thresholds.minConfidence) {
    return { targetLabel: CONFIG.reviewLabel, shouldStar: false, shouldArchive: false };
  }

  // 3. Non-action: assign category label and check archive policy
  var targetLabel = CONFIG.labels[bucket] || CONFIG.labels['${config.categories[config.categories.length - 1].key}'];
  var shouldArchive = CONFIG.archiveMap[bucket] !== false;

  return { targetLabel: targetLabel, shouldStar: false, shouldArchive: shouldArchive };
}

/**
 * Historical Jev classification (no star, no follow-up).
 */
function callJevHistoricalTriage(emailData, apiKey) {
  var payload = {
    model: CONFIG.model,
    state: {
      email: emailData,
    },
    questions: {
      bucket: {
        type: 'choice',
        instructions:
          'Which category does this historical email belong to?',
        criteria: {
${config.categories.map((c) => `          ${c.key}: ${JSON.stringify(c.description)},`).join('\n')}
        },
      },
    },
  };

  var options = {
    method: 'post',
    contentType: 'application/json',
    headers: {
      Authorization: 'Bearer ' + apiKey,
    },
    payload: JSON.stringify(payload),
    muteHttpExceptions: true,
  };

  var response = UrlFetchApp.fetch(CONFIG.typesafeEndpoint, options);
  var json = JSON.parse(response.getContentText());

  if (!json.answers || !json.answers.bucket) {
    throw new Error('TypeSafe API response error: ' + response.getContentText());
  }

  var bucket = json.answers.bucket.choice;
  var bucketConf = json.answers.bucket.confidence || 1.0;

  if (bucketConf < CONFIG.thresholds.minConfidence) {
    return { targetLabel: CONFIG.reviewLabel };
  }

  var targetLabel = CONFIG.labels[bucket] || CONFIG.labels['${config.categories[config.categories.length - 1].key}'];
  return { targetLabel: targetLabel };
}

function applyDecision(thread, message, decision, labelObjects) {
  var label = labelObjects[decision.targetLabel];
  if (label) {
    thread.addLabel(label);
  }

  if (decision.shouldStar) {
    message.star();
  }

  if (decision.shouldArchive) {
    thread.moveToArchive();
  }
}

function getOrCreateLabels() {
  var labelMap = {};
  var allLabels = [CONFIG.actionLabel, CONFIG.reviewLabel];
  for (var key in CONFIG.labels) {
    allLabels.push(CONFIG.labels[key]);
  }
  for (var i = 0; i < allLabels.length; i++) {
    var name = allLabels[i];
    var label = GmailApp.getUserLabelByName(name);
    if (!label) {
      label = GmailApp.createLabel(name);
    }
    labelMap[name] = label;
  }
  return labelMap;
}

function hasAnySystemLabel(thread, labelObjects) {
  var threadLabels = thread.getLabels();
  for (var i = 0; i < threadLabels.length; i++) {
    var lName = threadLabels[i].getName();
    if (labelObjects[lName]) {
      return true;
    }
  }
  return false;
}

function threadHasLabel(thread, targetLabel) {
  var labels = thread.getLabels();
  for (var i = 0; i < labels.length; i++) {
    if (labels[i].getName() === targetLabel.getName()) return true;
  }
  return false;
}

function getExistingCategoryLabel(thread, labelObjects) {
  var labels = thread.getLabels();
  for (var i = 0; i < labels.length; i++) {
    var name = labels[i].getName();
    if (name !== CONFIG.actionLabel && labelObjects[name]) {
      return name;
    }
  }
  return null;
}
`;

fs.writeFileSync(path.join(rootDir, 'gas', 'Code.gs'), gasCodeContent, 'utf8');
fs.writeFileSync(path.join(rootDir, 'templates', 'Code-english.gs'), gasCodeContent, 'utf8');
console.log('[OK] Updated gas/Code.gs and templates/Code-english.gs');


